spring:
  application:
    name=spring-security-oauth2

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security-oauth2
    username: postgres
    password: admin@2024!
    platform: postgres
    hikari:
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: auto
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: trace

